config/routes.rb
Rails.application.routes.draw do
  root to: 'static#home'

  
 


  resources :users do 
    resources :workouts, only: [:new, :create, :edit, :show] do
      resources :comments
    end
  end

  resources :workouts, only: [ :update , :index, :destroy]

  
  # get "/register", to: "users#new", as: "register"
  # post "register", to: "users#create"
  get '/auth/:provider/callback', to: 'sessions#omniauth'
 
  post "/login", to: "sessions#create"
  get "/login", to: "sessions#new"
  get "/logout", to: "sessions#destroy"
  
  # get 'users/show'
  # get 'users/new'
  # post 'users/new'
  # get 'users/create'
  # get 'users/edit'
  # get 'users/update'
  # get 'users/destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates :text, presence: true
    belongs_to :user
    belongs_to :workout
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :username, uniqueness: true
    validates :username, presence: true
    has_many :workouts, :dependent => :delete_all
    
    has_many :comments, :dependent => :delete_all
    has_many :commented_workouts, through: :comments, source: :workout
end

app/models/workout.rb
class MucsleValidator < ActiveModel::Validator
    MUSCLE = ["chest", "back", "biceps", "triceps", "legs", "shoulders"]
    def validate(record)
        if !MUSCLE.include?(record.muscle.downcase)
            record.errors.add :base, "must have on of these muscles (Chest, Back, Biceps, Triceps, Legs, or Shoulders)"
        end
    end
end

class Workout < ApplicationRecord
    # MUSCLE = ["Chest", "Back", "Biceps", "Triceps", "Legs", "Shoulders"]
    belongs_to :user
    has_many :comments
    has_many :commented_users, through: :comments, source: :user
    
    validates :title, uniqueness: true
    validates :title, presence: true
    validates :muscle, presence: true


    scope :alpha, -> {order("workouts.title ASC")}
    # validate :muscle_is_valid?
    validates_with MucsleValidator

    # private
    #     def muscle_is_valid?
    #         if !MUSCLE.include?(self.musclegroup)
    #             self.errors.add(:musclegroup, "Must use Muscles Already Provided")
    #         end
    #     end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    include ApplicationHelper::SessionsHelper

    before_action :current_user

    private

    def authentication_required
        if !logged_in
            redirect_to "/login"
        end
    end
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_workout
    before_action :set_comment, only: [:edit, :update, :destroy]

    # def index
    # end

    def new
        @comment = Comment.new
    end

    def create
        @comment = @workout.comments.build(text: comment_params[:text], user: @current_user)
        if @comment.save
            redirect_to user_workout_path(@current_user, @workout)
        else
            @errors = @comment.errors.full_messages
            render :new
        end
    end

    def edit
    
    end
     
    def update 
        if @comment.update(comment_params)
            redirect_to user_workout_path(@current_user, @workout)
        else
            @errors = @comment.errors.full_messages
            render :edit
        end
    end

    # def show
    # end

    def destroy
        @comment.destroy
        redirect_to user_workout_path(@current_user, @workout)
    end



    private

        def set_workout
            @workout = Workout.find(params[:workout_id])
        end

        def set_comment 
            @comment = Comment.find(params[:id])
        end

        def comment_params
            params.require(:comment).permit(:text)
        end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        render :new
    end

    def create
        @user = User.find_by(:username => params[:username])
        if @user && @user.authenticate(params[:password])
            login(@user)
            redirect_to "/workouts"
        else
            redirect_to "/login", :notice => "Can't Locate User"
        end
    end

    def destroy
        reset_session
        redirect_to "/login"
    end

    def omniauth
        user = User.find_or_create_by(uid: auth['uid'], provider: auth['provider']) do |u|
            u.username = auth['info']['first_name']
            u.password = SecureRandom.hex(10)
        end
        if user.valid?
            login(user)
            redirect_to "/workouts"
        else
            redirect_to "/login"
        end
    end
    
    private

    def auth
        request.env['omniauth.auth']
    end
end

#     private

#     def user_params
#         params.require(:username).permit(:username, :password_digest)
#     end

app/controllers/static_controller.rb
class StaticController < ApplicationController

def home
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]

    def new
        @user = User.new
    end


    def create
        @user = User.new(user_params)
        if @user.save
            login(@user)
            redirect_to "/workouts"
        else
            @errors = @user.errors.full_messages
            render :new
        end

    end

    def show
    end

    def edit
    end

    def update
        if @user.update(user_params)
            redirect_to user_path
        else
            @errors = @user.errors.full_messages
            render :edit
        end
    end

    def destroy
        @user.destroy
        reset_session
        redirect_to root_path
    end


    private
        def user_params
            params.require(:user).permit(:username, :password)
        end

        def set_user
            @user = current_user
        end

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
    before_action :set_workout, only: [:show, :edit, :update, :destroy]
    before_action :authentication_required


    def index
        @workouts = Workout.alpha
    end

    def show
    end
  
    def new
        @workout = Workout.new
    end
  
    def create
        @workout = current_user.workouts.build(workout_params)
        if @workout.save
            redirect_to workouts_path
        else
            @errors = @workout.errors.full_messages
            render :new
        end
    end
  
    def update
        if @workout.update(workout_params)
            redirect_to workouts_path
        else
            @errors = @workout.errors.full_messages
            render :edit
        end
    end
  
    def destroy
        @workout.destroy
        redirect_to workouts_path
    end

    private

    def set_workout
        @workout = Workout.find_by_id(params[:id])
    end

    def workout_params
        params.require(:workout).permit(:title, :muscle)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    module SessionsHelper
        
        def logged_in
        current_user ? true : false
        end


        def current_user
            if session[:current_user_id]
                @current_user ||= User.find(session[:current_user_id])
            end
        end

        def login(user)
            session[:current_user_id] = user.id
        end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/musclegroup_helper.rb
module MusclegroupHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/comments/_form.html.erb
   <h2> <%= action %> </h2>

   <% if @errors %>
    <% @errors.each do |e| %>
    <h6> <%= e %> </h6>
    <%end%>
    <%end%>

    <%= form_for [@current_user, @workout, comment]  do |t|%><br>
        <%= t.label "Comment" %><br>
        <%= t.text_field :text %><br>
        <%= t.submit %>
    <% end %>

app/views/comments/edit.html.erb
<%= render partial: "comments/form", locals: {comment: @comment, action: "Edit Comment"} %>
<%= button_to  "Delete", user_workout_comment_path(@current_user, @workout, @comment), method: "delete" %>

app/views/comments/new.html.erb
<%= render partial: "comments/form", locals: {comment: @comment, action: "New Comment"} %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>WorkoutGroup App</title>

     <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <% if session[:current_user_id] %>
    <nav>
      Hello, <%= @current_user.username %> !
    </nav>
    <%end%>
  
    <%= render "static/header" %>
    <div class="container">
    <br>
    <%= yield %>
    </div>
  

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/users/_form.html.erb
<h1> <%= action %> </h1>
<br>
<% if @errors %>
    <% @errors.each do |e| %>
    <h6> <%= e %> </h6>
    <%end%>
<%end%>
<br>
    <%= form_for user do |t|%><br>
        <%= t.label "Username:" %><br>
        <%= t.text_field :username %><br>

        <%= t.label "Password:" %><br>
        <%= t.password_field :password %><br>
        <%= t.submit  %>
    <% end %>

app/views/users/edit.html.erb
<%= render partial: "users/form", locals: {user: @user, action: "Change Username / Password" } %>

app/views/users/new.html.erb
<%= render partial: "users/form", locals: {user: @user, action: "Sign Up!" } %><br>
<%= button_to "Sign Up With Google", '/auth/google_oauth2' %>

app/views/users/show.html.erb
<h1>My Profile</h1>

<% if @current_user.workouts.length > 0 %>
  <h4> My Workouts! </h4>
  <% @current_user.workouts.each do |w| %>
      <p> <%= link_to w.title, user_workout_path(@current_user,w) %> </p>
  <% end %>
<% else %>
  <h4> You have not created any workouts ! </h4>
<% end %>
<br>

<h6><%= link_to "Change Username/Password", edit_user_path(@current_user) %></h6><br>
<h6><%= link_to "Delete Account", user_path(@current_user), method: "delete" %></h6>

app/views/workouts/edit.html.erb
<h1>Edit Your Workout</h1>
<br>
<% if @errors %>
    <% @errors.each do |e| %>
    <h6> <%= e %> </h6>
    <%end%>
<%end%>

<%= form_for @workout, url: workout_path do |w| %>
    <div>
        <%= w.label :title %>
        <%= w.text_field :title %>
    </div>

    <div>
        <%= w.label :muscle %>
        <%= w.text_field :muscle %>
    </div>

    <%= w.submit "Submit" %>
    <% end %>
    <br>
    <br>
    Only Creator Can Edit Workout
    <br>
    Created by <%= @workout.user.username%>

app/views/workouts/index.html.erb
<h4> All Workouts! </h4>
<% @workouts.each do |w| %>  
    <p> <%= link_to w.title, user_workout_path(@current_user,w) %> </p>
<% end %>
<br>
<br>

<%# <h4> Create Workout - Click Below - Link to Create - takes to workouts/new </h4> %>
<%# 
<h4> <%= link_to "Create Workout", new_workout_path%> 

app/views/workouts/new.html.erb
<% if @errors %>
    <% @errors.each do |e| %>
    <h6> <%= e %> </h6>
    <%end%>
<%end%>

<%= form_for @workout, url: user_workouts_path do |w| %>
    <div>
        <%= w.label :title %>
        <%= w.text_field :title %>
    </div>

    <div>
        <%= w.label :muscle %>
        <%= w.text_field :muscle %> <p style="font-size:10px;"> make this small </p>
    </div>

    <%= w.submit "Create Workout" %>

    <% end %>

app/views/workouts/show.html.erb
<h5> Exercise: <%= @workout.title %> </h5>
<h5> Muscle: <%= @workout.muscle %> </h5>

<h6> Comments: </h6>

<ul>
  <% @workout.comments.each do |comment|%>
    <li><%= comment.user.username %> - <%= comment.text %> <%= @current_user == comment.user ? (link_to 'edit', edit_user_workout_comment_path(@current_user, @workout, comment)) : "" %></li>
  <% end %>
</ul>


<% if @current_user.workouts.include? @workout %>
  <%= link_to "Edit Workout", edit_user_workout_path(@current_user, @workout) %> 
  <br>
  <%= link_to "Delete Workout", workout_path(@workout), method: "delete" %> 
<% end %>
<br>
<br>
Created by <%= @workout.user.username%>
<br>
<%= link_to "New Comment", new_user_workout_comment_path(@current_user, @workout) %>